spring:
  #  application:
  #    name: coupons-service-loc # 本服务的名称
  datasource: # druid数据源
    name: ${datasource.name} # 本服务的数据源名称
    #    minIdle: ${datasource.minIdle}
    #    validationQuery: ${datasource.validationQuery}
    #    initialSize: ${datasource.initialSize}
    #    maxWait: ${datasource.maxWait}
    #    poolPreparedStatements: ${datasource.poolPreparedStatements}
    #    filters: ${datasource.filters}
    type: ${datasource.type} # 数据源类型
    driver-class-name: ${datasource.driver-class-name} # 数据源驱动类名称
    url: ${datasource.base.url} # 本服务的数据源路径
    username: ${datasource.username} # 本服务的数据源用户名
    password: ${datasource.password} # 本服务的数据源用户密码